### PR TITLE
Firmware reflash update

### PR DESCRIPTION
**Pull request by not-matt**
Development branch to resolve errors in previous update.

### CODE REVIEW

**Comment by ahodges9** [comment]
Looks like there are really two parts to the PR. FW updates to the new protocol and fixes for the various effects. You should sperate them out. I have a different PR update that address the FW side and has some advantages over what is currently here. We obviously need to do some testing with FastLED to ensure there are not issues, but from my testing it works better and fixes some glitches I has having with the strips.

**Comment by not-matt** [comment]
Is this a case of FastLED over NeoPixelBus? So far NPB has worked very
well. If there are any significant advantages to FastLED, could you briefly
run through them please?

**Comment by ahodges9** [comment]
FastLED is a much more active community and by far the most used. The biggest advantage though is that it works for virtually any LED strip and not just WS2812Bs . So I have a bunch of WS2801s that can be used now. There are lots of threads out there (i.e. https://forum.arduino.cc/index.php?topic=356405.0) about the advantages of FastLED.

The only reason people really use NeoPixel's library still is because Adafruit completely dominated the market early on. Always helps to be first... Most people buying individually addressable LEDs were buying NeoPixels which included all the samples using their own library. FastLED just came along later but IMO is by far better due to the active community.

**Comment by ahodges9** [comment]
One other thing is that FastLED has tons of features for running animations. For non-reactive effects it is probably better to have the FW manage them (will not have any glitches from network instability). So the controller just says enable effect XXX and the ESP8266 is capable of driving the effects itself. Doing this well with NeoPixelBus is quite a bit of work (as you have to manage pretty much everything yourself), with FastLED you can build great effects with just a line or two. There are also tons of sample effects already done that can be easily incorporated (see https://github.com/atuline/FastLED-Demos)

**Pull request merged**
